### ISSUE TITLE
Dragging file onto page when not in edit mode won't accept the drop

### ISSUE THREAD

**Issue by neandrake** [neandrake/haste-server#24]
I think this is because of how the body tag works. When in edit mode a textarea component is taking up the full dimension of the page. When not in edit mode the body tag is only the size of the text pasted.

Might be fixed with adding:

``` css
html {overflow-y:hidden; height: 100%;}
body {overflow-y:auto; height: 100%;}
```
